FROM python:3.8-slim as base

FROM base as builder
# Any python libraries that require system libraries to be installed will likely
# need the following packages in order to build
RUN apt-get update && apt-get install -y build-essential git

ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

ENV PATH=$PATH:/install/bin

RUN pip install stac_fastapi.api==2.3.0 stac_fastapi.pgstac==2.3.0 uvicorn==0.17.6