FROM ubuntu:20.04

# Setup timezone info
ENV TZ=UTC

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y software-properties-common

RUN add-apt-repository ppa:ubuntugis/ppa && \
     apt-get update && \
     apt-get install -y build-essential python3-dev python3-pip \
     jq unzip ca-certificates wget curl && \
     apt-get autoremove && apt-get autoclean && apt-get clean

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# See https://github.com/mapbox/rasterio/issues/1289
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

RUN python -m pip install --upgrade pip

# Install azure-cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install dev dependencies

COPY requirements-dev.txt /opt/src/requirements-dev.txt
RUN cd /opt/src && pip install -r requirements-dev.txt

#
# Copy and install packages
#

COPY pctasks/core /opt/src/pctasks/core
RUN cd /opt/src/pctasks/core && \
     pip install -e .

COPY pctasks/cli /opt/src/pctasks/cli
RUN cd /opt/src/pctasks/cli && \
     pip install -e .

COPY pctasks/task /opt/src/pctasks/task
RUN cd /opt/src/pctasks/task && \
     pip install -e .

COPY pctasks/submit /opt/src/pctasks/submit
RUN cd /opt/src/pctasks/submit && \
     pip install -e .

COPY pctasks/ingest /opt/src/pctasks/ingest
RUN cd /opt/src/pctasks/ingest && \
     pip install -e .

COPY pctasks/ingest_task /opt/src/pctasks/ingest_task
RUN cd /opt/src/pctasks/ingest_task && \
     pip install -e .

COPY pctasks/execute /opt/src/pctasks/execute
RUN cd /opt/src/pctasks/execute && \
     pip install -e .

COPY pctasks/dataset /opt/src/pctasks/dataset
RUN cd /opt/src/pctasks/dataset && \
     pip install -e .

COPY pctasks/notify /opt/src/pctasks/notify
RUN cd /opt/src/pctasks/notify && \
     pip install -e .


COPY pctasks/dev /opt/src/pctasks/dev
RUN cd /opt/src/pctasks/dev && \
     pip install -e .[server]

# Setup Python Path to allow import of test modules
ENV PYTHONPATH=/opt/src:$PYTHONPATH

WORKDIR /opt/src
