services:
  task-base:
    container_name: pctasks-task-base
    image: pctasks-task-base
    build:
      context: .
      dockerfile: Dockerfile.task_base
    environment:
      - AZURE_TENANT_ID=${tenantId}
      - AZURE_CLIENT_ID=${servicePrincipalId}
      - AZURE_CLIENT_SECRET=${servicePrincipalKey}
    volumes:
      - ./pctasks:/opt/src
  ingest:
    container_name: pctasks-ingest
    image: pctasks-ingest
    build:
      context: pctasks
      dockerfile: ingest_task/Dockerfile
    environment:
      - AZURE_TENANT_ID=${tenantId}
      - AZURE_CLIENT_ID=${servicePrincipalId}
      - AZURE_CLIENT_SECRET=${servicePrincipalKey}
    volumes:
      - ./pctasks:/opt/src
  run:
    container_name: pctasks-run
    image: pctasks-run
    build:
      context: pctasks
      dockerfile: run/Dockerfile
    environment:
      - AZURE_TENANT_ID=${tenantId}
      - AZURE_CLIENT_ID=${servicePrincipalId}
      - AZURE_CLIENT_SECRET=${servicePrincipalKey}
    volumes:
      - ./pctasks:/opt/src

networks:
  default:
    external: true
    name: pctasks-network

