FROM mcr.microsoft.com/azurelinux/base/python:3.12

RUN \
    tdnf update -y && \
    tdnf ca-certificates curl -y

ENV PATH=$PATH:/install/bin

RUN pip install stac_fastapi.api==2.4.1 stac_fastapi.pgstac==2.4.1 uvicorn==0.17.6

RUN mkdir -p /opt/src
COPY dev/stacapi.py /opt/src/stacapi.py
WORKDIR /opt/src
