{{- if .Values.secretProvider.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.providerName }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Values.secretProvider.kubernetesCertificateSecretName }}
    type: kubernetes.io/tls
    data:
    - objectName: {{ .Values.secretProvider.keyvaultCertificateName }}
      key: tls.crt
    - objectName: {{ .Values.secretProvider.keyvaultCertificateName }}
      key: tls.key
  parameters:
    usePodIdentity: "false"
    clientID: "{{ .Values.secretProvider.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.secretProvider.keyvaultName }}"
    tenantId: "{{ .Values.secretProvider.tenantId }}"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: {{ .Values.secretProvider.keyvaultCertificateName }}
          objectType: secret
{{- end }}