environment: "staging"
namespace: "default"

stac:
  enabled: true

tiler:
  enabled: true

pcingress:
  services:
    stac:
      path: ""
      name: ""
      port: ""
    tiler:
      path: ""
      name: ""
      port: ""

  cert:
    secretName: ""

  certIssuer:
    enabled: false
    privateKeySecretRef: "letsencrypt-staging"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    issuerEmail: ""

  ingress:
    enabled: false
    tlsHost: ""
    hosts: []
    annotations: {}

secretProvider:
  create: true
  providerName: "keyvault"
  userAssignedIdentityID: ""
  tenantId: ""
  keyvaultName: ""
  keyvaultCertificateName: ""
  kubernetesCertificateSecretName: ""

nameOverride: ""
fullnameOverride: ""
