environment: "staging"
namespace: "default"

stac:
  enabled: true

tiler:
  enabled: true

pcingress:
  services:
    stac:
      path: ""
      name: ""
      port: ""
    tiler:
      path: ""
      name: ""
      port: ""

  cert:
    secretName: ""

  ingress:
    enabled: false
    tlsHost: ""
    hosts: []
    annotations: {}

secretProvider:
  create: true
  providerName: "keyvault"
  namespace: ""
  userAssignedIdentityID: ""
  tenantId: ""
  keyvaultName: ""
  keyvaultCertificateName: ""
  kubernetesCertificateSecretName: ""

nameOverride: ""
fullnameOverride: ""
