# Default table names
DEFAULT_DATASET_TABLE_NAME = "datasets"

DEFAULT_WORKFLOW_RUN_RECORD_TABLE_NAME = "workflowrunrecords"
DEFAULT_JOB_RUN_RECORD_TABLE_NAME = "jobrunrecords"
DEFAULT_TASK_RUN_RECORD_TABLE_NAME = "taskrunrecords"

DEFAULT_IMAGE_KEY_TABLE_NAME = "imagekeys"
DEFAULT_WEBHOOKS_TABLE_NAME = "webhooks"
DEFAULT_BLOB_TRIGGER_REGISTRATION_TABLE_NAME = "blobtriggerregistrations"

# Default queue names
DEFAULT_INBOX_QUEUE_NAME = "inbox"
DEFAULT_SIGNAL_QUEUE_NAME = "tasksignals"
DEFAULT_WORKFLOW_QUEUE_NAME = "workflows"
DEFAULT_NOTIFICATIONS_QUEUE_NAME = "notifications"
DEFAULT_OPERATIONS_QUEUE_NAME = "operations"

# Default log container
DEFAULT_LOG_CONTAINER = "tasklogs"
DEFAULT_TASK_IO_CONTAINER = "taskio"
DEFAULT_CODE_CONTAINER = "code"

# Message types
TASK_SUBMIT_MESSAGE_TYPE = "Task"
WORKFLOW_SUBMIT_MESSAGE_TYPE = "Workflow"
NOTIFICATION_MESSAGE_TYPE = "Notification"
EVENTGRID_MESSAGE_TYPE = "EventGrid"
OPERATION_MESSAGE_TYPE = "DatasetOperation"

# Operation targets
DATASET_OPERATION_TARGET = "dataset"

# Settings
SETTINGS_DIR_ENV_VAR = "PCTASKS_SETTINGS_DIR"
SETTINGS_ENV_DIR = "~/.pctasks"
DEFAULT_PROFILE = "default"
ENV_VAR_PCTASK_PREFIX = "PCTASKS_"
ENV_VAR_PCTASKS_PROFILE = "PCTASKS_PROFILE"

ENV_VAR_TASK_APPINSIGHTS_KEY = "TASK_APPINSIGHTS_INSTRUMENTATIONKEY"

MICROSOFT_OWNER = "microsoft"

# Schema versions

WORKFLOW_SCHEMA_VERSION = "1.0.0"
TASK_CONFIG_SCHEMA_VERSION = "1.0.0"
TASK_RUN_CONFIG_SCHEMA_VERSION = "1.0.0"
TASK_RESULT_SCHEMA_VERSION = "1.0.0"
TASK_RUN_SIGNAL_SCHEMA_VERSION = "1.0.0"

RECORD_SCHEMA_VERSION = "1.0.0"

# Target environment
DEFAULT_TARGET_ENVIRONMENT = "default"

# Azurite environment
AZURITE_STORAGE_ACCOUNT_ENV_VAR = "AZURITE_STORAGE_ACCOUNT"
AZURITE_HOST_ENV_VAR = "AZURITE_HOST"
AZURITE_PORT_ENV_VAR = "AZURITE_PORT"
