name: stac-geoparquet
dataset: microsoft/stac-geoparquet
id: stac-geoparquet

jobs:
  stac:
    tasks:
      - id: create
        image: pccomponentstest.azurecr.io/pctasks-stac-geoparquet:2023.7.10.1
        code:
          src: ${{ local.path(pc_stac_geoparquet.py) }}
        task: pc_stac_geoparquet:StacGeoparquetTask
        args:
          table_account_url: "https://pctapisstagingsa.table.core.windows.net"
          table_name: "collectionconfig"
          storage_options_account_name: "pcstacitems"
          collections: "io-lulc-annual-v02"
        environment:
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.task-application-insights-connection-string }}
          STAC_GEOPARQUET_CONNECTION_INFO: ${{secrets.pgstac-connection-string}}
