name: stac-geoparquet
dataset: stac-geoparquet
id: stac-geoparquet

jobs:
  geoparquet:
    tasks:
      - id: update
        image: pccomponents.azurecr.io/pctasks-stac-geoparquet:guhidalgo
        code:
          src: ${{ local.path(pc_stac_geoparquet.py) }}
          requirements: ${{ local.path(./requirements.txt) }}
        task: pc_stac_geoparquet:StacGeoparquetTask
        # tags:
        #   # temporarily set this when creating the geoparquet files
        #   # for a new collection to avoid OOM kills
        #   batch_pool_id: tsk_db_gr
        args:
          table_account_url: "https://pcapi.table.core.windows.net"
          table_name: "greencollectionconfig"
          storage_options_account_name: "pcstacitems"
          # collections: "hls2-l30" # Set if you want to generate only one geoparquet file
          extra_skip:
            - "chesapeake-lc-13"
            - "chesapeake-lc-7"
            - "chesapeake-lu"
            - "drcog-lulc"
        environment:
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.task-application-insights-connection-string }}
          STAC_GEOPARQUET_CONNECTION_INFO: ${{secrets.pgstac-connection-string}}
