name: "Streaming workflow example"

args:
  - registry
  - queue_account_url # "https://pctaskstestdev.queue.core.windows.net"
  - cosmosdb_url #  "https://cdb-pctaskstest-dev.documents.azure.com:443/"

jobs:
  create-items:
    id: create-items
    tasks:
      - id: create-items
        image: "${{ args.registry }}/pctasks-goes-glm:2023.8.1.0"
        task: pctasks.dataset.streaming:StreamingCreateItemsTask
        code:
          src: datasets/goes/goes-glm/goes_glm.py
        args:
          streaming_options:
            queue_url: "${{args.queue_account_url}}/goes-glm"
            visibility_timeout: 30
            min_replica_count: 0
            max_replica_count: 10
            polling_interval: 30
            trigger_queue_length: 100
            allow_spot_instances: true
            resources:
              limits:
                cpu: "0.25"
                memory: "2Gi"
              requests:
                cpu: "0.25"
                memory: "2Gi"

          options:
            skip_validation: false
          create_items_function: goes_glm:GoesGlmCollection.create_item
          collection_id: "goes-glm"

        environment:
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.task-application-insights-connection-string }}
          PCTASKS_COSMOSDB__URL: ${{ args.cosmosdb_url }}
        schema_version: 1.0.0
is_streaming: True
schema_version: 1.0.0
id: goes-glm-streaming-test
dataset: goes_glm
