name: "Streaming workflow example"

env:
  AZURE_CLIENT_ID: ${ secrets.task_sp_whatever_id }

jobs:
  create-items:
    id: create-items
    tasks:
    - id: create-items
      image: "pccomponentstest.azurecr.io/pctasks-goes-glm:2023.2.27.0"
      task: pctasks.dataset.streaming:StreamingCreateItemsTask
      code:
        src: datasets/goes/goes-glm/goes_glm.py
      args:
        streaming_options:
          queue_url: "https://pclowlatency.queue.core.windows.net/goes-glm"
          visibility_timeout: 30
          min_replica_count: 0
          max_replica_count: 10
          polling_interval: 30
          trigger_queue_length: 100
        options:
          skip_validation: false
        cosmos_endpoint: https://pclowlatencytesttom.documents.azure.com:443/
        db_name: lowlatencydb
        container_name: items
        create_items_function: goes_glm:GoesGlmCollection.create_item
        collection_id: "goes-glm"
      schema_version: 1.0.0
is_streaming: True
schema_version: 1.0.0
id: goes-glm-streaming-test
dataset: goes_glm