{{- if .Values.pctasks.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pctasks.serviceAccountName" . }}
  labels:
    {{- include "pctasks.labels" . | nindent 4 }}
  {{- with .Values.pctasks.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pctasks-server-argoworkflows-workflow-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "pctasks.serviceAccountName" . }}
roleRef:
  kind: Role
  name: argo-workflows-workflow
  apiGroup: rbac.authorization.k8s.io

{{- end }}
