name: Process items for noaa-climate-normals-tabular
tokens:
  noaanormals:
    containers:
      climate-normals:
        token: ${{ pc.get_token(noaanormals, climate-normals) }}
args:
- registry
jobs:
  create-splits:
    id: create-splits
    tasks:
    - id: create-splits
      image: ${{ args.registry }}/pctasks-noaa-climate-normals:latest
      code:
        src: datasets/noaa-climate-normals/noaa_climate_normals.py

      task: noaa_climate_normals:NoaaClimateNormalsTabular.create_splits_task
      args:
        inputs:
        - uri: blob://noaanormals/climate-normals/normals-hourly/1981-2010/
          sas_token: ${{ pc.get_token(noaanormals, climate-normals) }}
          chunk_options:
            chunk_length: 1
            name_starts_with: access
            extensions:
            - .csv
            limit: 1
            list_folders: false
            chunk_file_name: uris-list
            chunk_extension: .csv
        options: {}
      schema_version: 1.0.0
  create-chunks:
    id: create-chunks
    tasks:
    - id: create-chunks
      image: ${{ args.registry }}/pctasks-noaa-climate-normals:latest
      code:
        src: datasets/noaa-climate-normals/noaa_climate_normals.py

      task: pctasks.dataset.chunks.task:create_chunks_task
      args:
        src_uri: ${{ item.uri }}
        dst_uri: blob://noaanormals/normals-etl-data/tabular/hourly-2023-01-11-1981-2010/assets
        options: ${{ item.chunk_options }}
      schema_version: 1.0.0
    foreach:
      items: ${{ jobs.create-splits.tasks.create-splits.output.splits }}
      flatten: true
    needs: create-splits
  process-chunk:
    id: process-chunk
    tasks:
    - id: create-items
      image: ${{ args.registry }}/pctasks-noaa-climate-normals:latest
      code:
        src: datasets/noaa-climate-normals/noaa_climate_normals.py

      task: noaa_climate_normals:NoaaClimateNormalsTabular.create_items_task
      args:
        asset_chunk_info:
          uri: ${{ item.uri }}
          chunk_id: ${{ item.chunk_id }}
        item_chunkset_uri: blob://noaanormals/normals-etl-data/tabular/hourly-2023-01-11-1981-2010/items
        collection_id: noaa-climate-normals-tabular
        options:
          skip_validation: false
      tags:
        batch_pool_id: high_memory_pool
      schema_version: 1.0.0
    - id: ingest-items
      image_key: ingest
      task: pctasks.ingest_task.task:ingest_task
      args:
        content:
          type: Ndjson
          uris:
          - ${{tasks.create-items.output.ndjson_uri}}
        options:
          insert_group_size: 5000
          insert_only: false
      schema_version: 1.0.0
    foreach:
      items: ${{ jobs.create-chunks.tasks.create-chunks.output.chunks }}
      flatten: true
    needs: create-chunks
schema_version: 1.0.0
id: test_noaa-climate-normals-tabular_process-items_hourly_1981-2010
dataset: noaa_climate_normals

