#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") DATASET [COMMAND]

Applies a code formatter to this codebase.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [[ "${1}" == "--help" ]]; then
        usage
    else
        docker-compose \
            -f docker-compose.console.yml \
            run --rm \
            dev \
            scripts/bin/format

    fi
fi
