#!/bin/bash

set -e

echo "== Generating requirements.txt ..."
pip_compile_options="--verbose"

docker-compose \
    -f docker-compose.console.yml \
    run --rm \
    dev \
    scripts/bin/pctasks-pip-compile ./pctasks/core/pyproject.toml -o pctasks/core/requirements.txt $pip_compile_options

docker-compose \
    -f docker-compose.console.yml \
    run --rm \
    dev \
    scripts/bin/pctasks-pip-compile ./pctasks/cli/pyproject.toml -o pctasks/cli/requirements.txt $pip_compile_options

docker-compose \
    -f docker-compose.console.yml \
    run --rm \
    dev \
    scripts/bin/pctasks-pip-compile ./pctasks/task/pyproject.toml -o pctasks/task/requirements.txt $pip_compile_options

docker-compose \
    -f docker-compose.console.yml \
    run --rm \
    dev \
    scripts/bin/pctasks-pip-compile ./pctasks/client/pyproject.toml -o pctasks/client/requirements.txt $pip_compile_options

docker-compose \
    -f docker-compose.console.yml \
    run --rm \
    dev \
    scripts/bin/pctasks-pip-compile ./pctasks/ingest/pyproject.toml -o pctasks/ingest/requirements.txt $pip_compile_options

# docker-compose \
#     -f docker-compose.console.yml \
#     run --rm \
#     dev \
#     scripts/bin/pctasks-pip-compile ./pctasks/ingest_task/setup.py -o pctasks/ingest_task/requirements.txt $pip_compile_options

# docker-compose \
#     -f docker-compose.console.yml \
#     run --rm \
#     dev \
#     scripts/bin/pctasks-pip-compile ./pctasks/run/pyproject.toml -o pctasks/run/requirements.txt $pip_compile_options

# docker-compose \
#     -f docker-compose.console.yml \
#     run --rm \
#     dev \
#     pip-compile ./pctasks/server/pyproject.toml --extra dev -o pctasks/server/requirements.txt $pip_compile_options
