#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [submit|ingest|func|deploy]
Installs python projects into local environment.
"
}

while [[ $# -gt 0 ]]; do case $1 in
    --help)
        usage
        exit 0
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        shift
        shift
        ;;
    esac done

source scripts/env

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    pip install uv
    # Dependencies must be mutually compatible across all projects
    uv pip install --prerelease allow --python=$(which python3) \
        -r "pctasks/core/requirements.txt" \
        -r "pctasks/cli/requirements.txt" \
        -r "pctasks/task/requirements.txt" \
        -r "pctasks/client/requirements.txt" \
        -r "pctasks/ingest/requirements.txt" \
        -r "pctasks/ingest_task/requirements.txt" \
        -r "pctasks/dataset/requirements.txt" \
        -r "pctasks/run/requirements.txt" \
        -r "pctasks/notify/requirements.txt" \
        -r "pctasks/router/requirements.txt" \
        -r "pctasks/server/requirements.txt" \
        -r "pctasks/dev/requirements.txt" \
        -r "requirements-dev.txt"
    for DIR in "${PACKAGE_DIRS[@]}"; do
        echo "Installing ${DIR}"
        uv pip install --system --no-deps -e ${DIR}
    done
fi
