#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    if [[ "${1}" ]]; then
        echo "${1}"
    fi

    echo -n \
        "Usage: $(basename "$0") --acr ACR_NAME --tag IMAGE_TAG
Tags and pushes task images.

ACR_NAME - The ACR repository name.
IMAGE_TAG - The tag to use for all images.
"
}

# Parse args

while [[ "$#" -gt 0 ]]; do case $1 in
    --acr)
        ACR_NAME=$2
        shift
        shift
        ;;
    --tag)
        IMAGE_TAG=$2
        shift
        shift
        ;;
    --help)
        usage
        exit 0
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        shift
        shift
        ;;
    esac done

function publish() {
    local IMAGE_NAME=$1
    local full_image_name="${ACR_NAME}.azurecr.io/${IMAGE_NAME}:${IMAGE_TAG}"
    docker tag ${IMAGE_NAME} ${full_image_name}
    docker push ${full_image_name}
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1}" == "--help" ]; then
        usage
    else
        # Login
        az acr login -n ${ACR_NAME}

        # Ingest
        publish pctasks-ingest

    fi

fi
