#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [down]
Runs the development servers

--detached
    Run the servers in detached mode
--no-aux-servers
    Don't run non-essential devevelopment environment servers
down
    Stop the servers
"
}

DETACHED_ARG=""
STOP_SERVERS=""
AUX_SERVERS="-f docker-compose.aux.yml"

while [[ "$#" -gt 0 ]]; do case $1 in
    down)
        STOP_SERVERS="TRUE"
        shift
        ;;
    --detached)
        DETACHED_ARG="--detach"
        shift
        ;;
    --no-aux-servers)
        AUX_SERVERS=""
        shift
        ;;
    --help)
        usage
        exit 0
        shift
        ;;
    *) break ;;
    esac done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${STOP_SERVERS}" ]; then
        echo "Stopping servers"
        docker-compose -f docker-compose.yml -f docker-compose.aux.yml down
    else
        echo "Starting servers"
        docker-compose -f docker-compose.yml ${AUX_SERVERS} \
        up ${DETACHED_ARG} "$@"
    fi
fi
