#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    if [[ "${1}" ]]; then
        echo "${1}"
    fi
    echo -n \
        "Usage: $(basename "$0") [OPTIONS]
Runs tests.

Options:
    --subpackage <subpackage>
        Run tests only for a subpackage.
    --functions
        Run tests only for Azure Functions.
    --test-only
        Only run tests, don't lint
    --no-integration
        Skip running integration tests
    --integration-only
        Only run integration tests
    --lint-only
        Only run linting
    --no-init
        Don't initialize mypy, which is for installing stubs, but takes extra time if already run.
    --help
        Show this help

"
}

# Parse args
SUBPACKAGE=""
FUNCTIONS=""
TEST_ONLY=""
LINT_ONLY=""
NO_INTEGRATION=""
NO_INIT=""
while [[ $# -gt 0 ]]; do case $1 in
    --subpackage)
        SUBPACKAGE="--subpackage ${2}"
        shift
        shift
        ;;
    --functions)
        FUNCTIONS="--functions"
        shift
        ;;
    --test-only)
        TEST_ONLY="--test-only"
        shift
        ;;
    --lint-only)
        LINT_ONLY="--lint-only"
        shift
        ;;
    --no-integration)
        NO_INTEGRATION="--no-integration"
        shift
        ;;
    --integration-only)
        INTEGRATION_ONLY="--integration-only"
        shift
        ;;
    --no-init)
        NO_INIT="--no-init"
        shift
        ;;
    --help)
        usage
        exit 0
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        exit 1
        ;;
    esac done

# Don't run in tty if CI
TERM=(-it)
if [[ "${CI}" ]]; then
    TERM=()
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    docker-compose \
        -f docker-compose.console.yml \
        run --rm \
        dev \
        scripts/bin/test ${SUBPACKAGE} ${FUNCTIONS} ${TEST_ONLY} ${LINT_ONLY} ${NO_INTEGRATION} ${INTEGRATION_ONLY} ${NO_INIT}

fi
