# A Kubernetes Secret for authentication with the storage queues.
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  # This must match pctasks.run.workflow.kubernetes.KEDA_QUEUE_CONNECTION_STRING_AUTH_NAME
  # Must be in the same namespace as the KEDA Deployments.
  name: queue-connection-string-auth
spec:
  secretTargetRef:
  - parameter: connection
    # This Kubernetes Secret is created with terraform
    # The name must match the value in terraform/resources/aks.tf
    name: secrets-storage-queue-connection-string
    key: ConnectionString
