name: CI/CD

on:
  push:
    branches: [main]
    tags: ["*"]

env:
  PCTASKS_COSMOSDB__URL: ${{ secrets.COSMOSDB_URL }}
  PCTASKS_COSMOSDB__TEST_CONTAINER_SUFFIX: ${{ github.run_id }}

permissions:
  id-token: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.12"

      - name: Log in with Azure
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install local dependencies
        run: ./scripts/install

      - name: Setup
        run: ./scripts/setup --no-aux-servers

      - name: Test
        run: ./scripts/test

      - name: Validate collections
        run: ./scripts/validate-collections

      # Integration Tests

      - name: Install Kind
        uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07 # v1.4.0
        with:
          install_only: true

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.8.2
        if: ${{ github.base_ref  == 'main' }}

      - name: Setup cluster
        run: ./scripts/cluster setup

      # Disable integration tests for now
      # - name: Run integration tests
      #   run: ./scripts/citest-integration

      # Publish images

      - name: Get image tag
        id: get_image_tag
        run: case "${GITHUB_REF}" in
          *tags*)
          echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
          ;;
          *)
          echo "::set-output name=tag::latest"
          ;;
          esac

      - name: Publish images (test)
        run: ./scripts/publish --acr pccomponentstest --tag ${{steps.get_image_tag.outputs.tag}}

      - name: Publish images
        run: ./scripts/publish --acr pccomponents --tag ${{steps.get_image_tag.outputs.tag}}

      - name: Clean up CosmosDB test containers
        run: ./scripts/setup --rm-test-containers
        if: always()

    outputs:
      image_tag: ${{ steps.get_image_tag.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - build_and_publish
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Log in with Azure
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: ./scripts/cideploy
        env:
          IMAGE_TAG: ${{needs.build_and_publish.outputs.image_tag}}
          ENVIRONMENT: staging
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_USE_OIDC: true
