name: Publish function package (dev)

on:
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce" # v1.4.0
        with:
          fallback: 2022.2.0

      - name: "Get next minor version"
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@d079934efaf011a4cf8912d4637097fe35d32b93" # v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: "Publish package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/cipublish-pkgs -t "${{ steps.semvers.outputs.minor }}-dev"
