name: Publish function package (dev)

on:
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 2022.2.0

      - name: "Get next minor version"
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: "Publish package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/cipublish-pkgs -t "${{ steps.semvers.outputs.minor }}-dev"
