name: Publish function package (release)

on:
  push:
    tags: ["*"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Get tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 2022.2.0

      - name: "Publish package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/cipublish-pkgs -t "${{ steps.previoustag.outputs.tag }}"
